# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e33199c0832e6c1cacd80d2b08cd50de4375d4ed08e332a617f8a13f87a9d95d217615a78301b8d78dc37bf189602ca6b4d038a255c9eb9c45a96949ac124697

test:
  secret_key_base: b76f9a36ce856edaebd4fe0f6cb43e68aed768b1b929c1ca8717ab2f6a6010595c8a7665bad8e9bf24e5bd063c4c10358a2a7fe6120a574204b03e208d7d7769

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
